packages:
  - apps/*
  - packages/*

catalog:
  '@cloudflare/workers-types': ^4.20251213.0
  '@orpc/openapi': ^1.12.2
  '@orpc/server': ^1.12.2
  '@orpc/zod': ^1.12.2
  '@types/node': ^22.13.11
  better-auth: 1.4.9
  dotenv: ^17.2.2
  hono: ^4.8.2
  typescript: ^5
  zod: ^4.1.13
