const APP_BASE_URL =
  process.env.NEXT_PUBLIC_CALLBACK_URL || "http://localhost:3001";
const DEFAULT_LOGIN_REDIRECT = `${APP_BASE_URL}/dashboard`;
const DEFAULT_COMPLETE_REGISTRATION_REDIRECT = `${APP_BASE_URL}/auth/complete`;

export { APP_BASE_URL, DEFAULT_LOGIN_REDIRECT, DEFAULT_COMPLETE_REGISTRATION_REDIRECT };
